[graph]
# targets = [] # Disables all not explicitly listed targets
# exclude = [] # Also removes dependencies of package if not otherwise connected
all-features = true
no-default-features = false
# features = [] # We use all-features
exclude-dev = false

[output]
feature-depth = 1

[advisories]
version = 2
# db-path = "$CARGO_HOME/advisory-dbs"
# db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
    { id = "RUSTSEC-2024-0436", reason = "Unmaintained crate 'paste' in our tree" },
]
git-fetch-with-cli = false # False = use build in git library
yanked = "deny"

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "OFL-1.1",
    "Unicode-3.0",
    "Zlib",
    "MIT-0",
    "0BSD",
    "Ubuntu-font-1.0",
    "NCSA",
]
confidence-threshold = 0.93
# exceptions = []
include-dev = true
unused-allowed-license = "warn"

[bans]
multiple-versions = "deny"
multiple-versions-include-dev = false
wildcards = "deny"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
# allow = [] # Whitelist if one or more entries
# deny = []
skip = [
    { crate = "regex-automata@0.1.10", reason = "Old version used by other dependency" },
    { crate = "regex-syntax@0.6.29", reason = "Old version used by other dependency" },
    { crate = "bitflags@1.3.2", reason = "Old version used by other dependency" },
    { crate = "windows@0.54.0", reason = "Old version used by other dependency" },
    { crate = "windows-core@0.54.0", reason = "Old version used by other dependency" },
    { crate = "windows-sys@0.45.0", reason = "Old version used by other dependency" },
    { crate = "windows-targets@0.42.2 ", reason = "Old version used by other dependency" },
    { crate = "windows-targets@0.48.5", reason = "Old version used by other dependency" },
    { crate = "windows_aarch64_gnullvm@0.42.2", reason = "Old version used by other dependency" },
    { crate = "windows_aarch64_gnullvm@0.48.5", reason = "Old version used by other dependency" },
    { crate = "windows_aarch64_msvc@0.42.2", reason = "Old version used by other dependency" },
    { crate = "windows_aarch64_msvc@0.48.5", reason = "Old version used by other dependency" },
    { crate = "windows_i686_gnu@0.42.2", reason = "Old version used by other dependency" },
    { crate = "windows_i686_gnu@0.48.5", reason = "Old version used by other dependency" },
    { crate = "windows_i686_msvc@0.42.2", reason = "Old version used by other dependency" },
    { crate = "windows_i686_msvc@0.48.5", reason = "Old version used by other dependency" },
    { crate = "windows_x86_64_gnu@0.42.2", reason = "Old version used by other dependency" },
    { crate = "windows_x86_64_gnu@0.48.5", reason = "Old version used by other dependency" },
    { crate = "windows_x86_64_gnullvm@0.42.2", reason = "Old version used by other dependency" },
    { crate = "windows_x86_64_gnullvm@0.48.5", reason = "Old version used by other dependency" },
    { crate = "windows_x86_64_msvc@0.42.2", reason = "Old version used by other dependency" },
    { crate = "windows_x86_64_msvc@0.48.5", reason = "Old version used by other dependency" },
    { crate = "redox_syscall@0.4.1", reason = "Old version used by other dependency" },
    { crate = "base64@0.21.7", reason = "Old version used by other dependency" },
    { crate = "ndk@0.8.0", reason = "Old version used by other dependency" },
    { crate = "ndk-sys@0.5.0+25.2.9519653", reason = "Old version used by other dependency" },
    { crate = "windows-result@0.1.2", reason = "Old version used by other dependency" },
    { crate = "windows-sys@0.52.0", reason = "Old version used by other dependency" },
    { crate = "windows-sys@0.59.0", reason = "Old version used by other dependency" },
    { crate = "bit-set@0.5.3", reason = "Old version used by other dependency" },
    { crate = "bit-vec@0.6.3", reason = "Old version used by other dependency" },
    { crate = "core-foundation@0.9.4", reason = "Old version used by other dependency" },
    { crate = "ttf-parser@0.20.0", reason = "Old version used by other dependency" },
    { crate = "ttf-parser@0.21.1", reason = "Old version used by other dependency" },
    { crate = "windows@0.57.0", reason = "Old version used by other dependency" },
    { crate = "windows-core@0.57.0", reason = "Old version used by other dependency" },
    { crate = "windows-implement@0.57.0", reason = "Old version used by other dependency" },
    { crate = "windows-interface@0.57.0", reason = "Old version used by other dependency" },
    { crate = "windows@0.58.0", reason = "Old version used by other dependency" },
    { crate = "windows-implement@0.58.0", reason = "Old version used by other dependency" },
    { crate = "windows-interface@0.58.0", reason = "Old version used by other dependency" },
    { crate = "windows-result@0.2.0", reason = "Old version used by other dependency" },
    { crate = "windows-strings@0.1.0", reason = "Old version used by other dependency" },
    { crate = "windows-targets@0.52.6", reason = "Old version used by other dependency" },
    { crate = "windows_aarch64_gnullvm@0.52.6", reason = "Old version used by other dependency" },
    { crate = "windows_i686_gnu@0.52.6", reason = "Old version used by other dependency" },
    { crate = "windows_i686_msvc@0.52.6", reason = "Old version used by other dependency" },
    { crate = "windows_x86_64_gnu@0.52.6", reason = "Old version used by other dependency" },
    { crate = "windows_x86_64_gnullvm@0.52.6", reason = "Old version used by other dependency" },
    { crate = "windows_x86_64_msvc@0.52.6", reason = "Old version used by other dependency" },
    { crate = "windows-core@0.58.0", reason = "Old version used by other dependency" },
    { crate = "windows_aarch64_msvc@0.52.6", reason = "Old version used by other dependency" },
    { crate = "itertools@0.12.1", reason = "Old version used by other dependency" },
    { crate = "zerocopy@0.7.35", reason = "Old version used by other dependency" },
    { crate = "downcast-rs@1.2.1", reason = "Old version used by other dependency" },
    { crate = "getrandom@0.2.16", reason = "Old version used by other dependency" },
    { crate = "itertools@0.13.0", reason = "Old version used by other dependency" },
    { crate = "thiserror@1.0.69", reason = "Old version used by other dependency" },
    { crate = "thiserror-impl@1.0.69", reason = "Old version used by other dependency" },
    { crate = "wasi@0.11.0+wasi-snapshot-preview1", reason = "Old version used by other dependency" },
] # Only for duplicate detection
# skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
required-git-spec = "rev"
# private = []

# [sources.allow-org]
# github = []
# gitlab = []
# bitbucket = []
