[toolchain]
channel = "nightly"
components = [
    "rustc",
    "cargo",
    "rustfmt",
    "rust-std",
    "clippy",
    "miri",
    "rust-src",
]
targets = [
    # Linux
    "x86_64-unknown-linux-gnu",

    # Windows
    "x86_64-pc-windows-gnu",
]
profile = "default"
